version: '3'

services:

  web:
    image: 'bitnami/apache:${APACHE_VERSION}'
    ports:
      - '${WEB_PORT}:8080'
    volumes:
      - './configs/apache/vhosts:/bitnami/apache/conf/vhosts:cached'
      - '${WEB_PATH}:/app:cached'
    environment:
      - DISABLE_WELCOME_MESSAGE=1

  app:
    image: 'kodeline/app-php-fpm:1.0'
    build:
      context: .
      dockerfile: ./images/php-fpm/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    depends_on:
      - web
    ports:
      - '${SSH_PORT}:22'
    volumes:
      - '${WEB_PATH}:/app:cached'
    environment:
      - APP_DEBUG_MODE=${APP_DEBUG_MODE}

  front-tools:
    image: 'kodeline/front-tools:1.0'
    build:
      context: .
      dockerfile: ./images/gulp/Dockerfile
      args:
        - GULP_RUN_SCRIPT=${GULP_RUN_SCRIPT}
        - GULP_REPOSITORY=${GULP_REPOSITORY}
    restart: 'no'
    depends_on:
      - app
    volumes:
      - '${WEB_PATH}:/app:cached'
      - './configs/gulp/tools-config.json:/app-front-tools/cnf/config.json:cached'
    ports:
      - '${GULP_PORT}:${GULP_PORT}'
      - '${GULP_ADMIN_PORT}:${GULP_ADMIN_PORT}'
